name: .NET Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ControllersExample/ControllersExample.csproj

    - name: Build for linux-x64
      run: dotnet build ControllersExample/ControllersExample.csproj --configuration Release --runtime linux-x64 --no-restore

    - name: Build for linux-arm64
      run: dotnet build ControllersExample/ControllersExample.csproj --configuration Release --runtime linux-arm64 --no-restore

